language: bash
before_install:
  - sudo apt-get update
  - sudo apt-get install -y shellcheck
  - sudo apt-get install imagemagick
  - sudo apt-get install p7zip-full
  - sudo apt-get install ghostscript
  - ls -l
script:
  - wget "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/worldcupplayerinfo.tsv"
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
  - 7z x -ot web_log.tsv.7z
  - ls -l
  - cd chap0x04/  
  - cd shell/ 
  - echo "==============Task1================"
  - bash task1.sh -h
  - bash task1.sh -q 66
  - bash task1.sh -r 50%
  - bash task1.sh -w 20 black Hello,world
  - bash task1.sh -p pre
  - bash task1.sh -s suf
  - bash task1.sh -t
  - echo "==================================="
  - echo "==============Task2================"
  - bash task2.sh -h 
  - bash task2.sh -y
  - bash task2.sh -p 
  - bash task2.sh -l 
  - bash task2.sh -s 
  - echo "==================================="
  - echo "==============Task3================"
  - bash task3.sh -h 
  - bash task3.sh -a
  - bash task3.sh -b 
  - bash task3.sh -c 
  - bash task3.sh -d 
  - bash task3.sh -4 
  - bash task3.sh -e /elv/DELTA/uncons.htm
  - echo "==================================="
  - shellcheck task1.sh
  - echo "==================================="
  - shellcheck task2.sh
  - echo "==================================="
  - shellcheck task3.sh
  - echo "==================================="
notifications:
  email:
    on_success: never
